# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
addons:
  apt:
    packages:
      - libproj-dev
      - libgdal-dev

r_packages:
  - covr
  - devtools

r_github_packages:
  - xiayh17/eSetAnno

after_success:
  - Rscript -e 'covr::codecov()'
